// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXjVLDFB_0ECXWKoR_9dy8Ys_55pUK6Zw',
    appId: '1:73613507053:web:7a5eb13bf03795316f4fe4',
    messagingSenderId: '73613507053',
    projectId: 'marmot-lovers',
    authDomain: 'marmot-lovers.firebaseapp.com',
    storageBucket: 'marmot-lovers.firebasestorage.app',
    measurementId: 'G-E7G8WXN24N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpx95KMkPACBs_Wspi8-gJjepWlMMzK5U',
    appId: '1:73613507053:android:f986d6452a4a4a4f6f4fe4',
    messagingSenderId: '73613507053',
    projectId: 'marmot-lovers',
    storageBucket: 'marmot-lovers.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBv-Z44uuBChphFFAttgD0zl9EQHYAqsJg',
    appId: '1:73613507053:ios:92ef13fb6156e0e56f4fe4',
    messagingSenderId: '73613507053',
    projectId: 'marmot-lovers',
    storageBucket: 'marmot-lovers.firebasestorage.app',
    iosBundleId: 'com.marmota.marmotLovers',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBv-Z44uuBChphFFAttgD0zl9EQHYAqsJg',
    appId: '1:73613507053:ios:92ef13fb6156e0e56f4fe4',
    messagingSenderId: '73613507053',
    projectId: 'marmot-lovers',
    storageBucket: 'marmot-lovers.firebasestorage.app',
    iosBundleId: 'com.marmota.marmotLovers',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXjVLDFB_0ECXWKoR_9dy8Ys_55pUK6Zw',
    appId: '1:73613507053:web:e70e0223ef0ba2cd6f4fe4',
    messagingSenderId: '73613507053',
    projectId: 'marmot-lovers',
    authDomain: 'marmot-lovers.firebaseapp.com',
    storageBucket: 'marmot-lovers.firebasestorage.app',
    measurementId: 'G-XCDZXN66KM',
  );
}
